# SEO settings
title: "Devlog"
title2: "" # default: ""
description: "This is my Devlog"
keywords: "java, javascript, IT, development, frontend, backend"
url: https://ilhsu.github.io #site url
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-80638330-1
#repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "devlog-kairos"
#twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Do Hyun"
  job      : "Software Engineer"
  #bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  #thumb    : /images/author.jpg
  email    : ilhsu@naver.com
  #url      : http://heiswayi.github.io
  #github   : http://github.com/heiswayi
  #twitter  : http://twitter.com/HeiswayiNrird
  #facebook : https://www.facebook.com/profile.php?id=1257583160
  #linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "ko_KR"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
