# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Devlog
name: Do Hyun
email: ilhsu@naver.com
description:
encoding: utf-8
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ilhsu.github.com # the base hostname & protocol for your site
twitter_username: ilhsu
github_username:

permalink: /:year/:title/

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
